version: 2
jobs:
  build:
    docker:
      - image: docker:17.06.0-ce-git
    working_directory: /
    steps:
      - deploy:
          name: SSH to production and run deploy script
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan $DROPLET_IP >> ~/.ssh/known_hosts
            ssh -v $DROPLET_USER@$DROPLET_IP << EOF
              if [ ! -d personal-website ]; then
                git clone https://github.com/MarkAZhang/personal-website.git
              fi
              cd personal-website
              git pull origin master
              ./deploy.sh
            EOF
